"""neuster Stand

Revision ID: 0a51db1c6ca3
Revises: 75c4e6e1e1c4
Create Date: 2025-01-05 11:19:17.756627

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a51db1c6ca3'
down_revision = '75c4e6e1e1c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tree_type', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('tree_height', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('inclination', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('trunk_diameter', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.alter_column('latitude',
               existing_type=sa.NUMERIC(precision=8, scale=6),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_constraint('trees_tree_type_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('trees_initial_creator_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('trees_health_status_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('co2_stored')
        batch_op.drop_column('health_status_id')
        batch_op.drop_column('created_at')
        batch_op.drop_column('initial_creator_id')
        batch_op.drop_column('tree_type_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uname',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.NUMERIC(precision=8, scale=6),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=False)
        batch_op.alter_column('verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('salt',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=16),
               nullable=False)
        batch_op.alter_column('xp',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('xp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('salt',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.NUMERIC(precision=8, scale=6),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('uname',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tree_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('initial_creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('health_status_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('co2_stored', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('trees_health_status_id_fkey', 'health_statuses', ['health_status_id'], ['id'])
        batch_op.create_foreign_key('trees_initial_creator_id_fkey', 'users', ['initial_creator_id'], ['id'])
        batch_op.create_foreign_key('trees_tree_type_id_fkey', 'tree_types', ['tree_type_id'], ['id'])
        batch_op.alter_column('longitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=9, scale=6),
               existing_nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=8, scale=6),
               existing_nullable=False)
        batch_op.drop_column('address')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('trunk_diameter')
        batch_op.drop_column('inclination')
        batch_op.drop_column('tree_height')
        batch_op.drop_column('tree_type')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
