"""neuster Stand

Revision ID: 3c0dc0b9a158
Revises: 4f1f18859de6
Create Date: 2025-01-05 14:58:18.212048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0dc0b9a158'
down_revision = '4f1f18859de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_types', schema=None) as batch_op:
        batch_op.drop_constraint('account_types_type_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_types', schema=None) as batch_op:
        batch_op.create_unique_constraint('account_types_type_name_key', ['type_name'])

    # ### end Alembic commands ###
