"""neuster Stand

Revision ID: 4f1f18859de6
Revises: 0ed0afbd3066
Create Date: 2025-01-05 12:47:17.233233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f1f18859de6'
down_revision = '0ed0afbd3066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trust_levels', schema=None) as batch_op:
        batch_op.drop_constraint('trust_levels_rank_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trust_levels', schema=None) as batch_op:
        batch_op.create_unique_constraint('trust_levels_rank_key', ['rank'])

    # ### end Alembic commands ###
