"""not not null

Revision ID: 75c4e6e1e1c4
Revises: a3bcc08a4a84
Create Date: 2025-01-04 15:47:21.044916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c4e6e1e1c4'
down_revision = 'a3bcc08a4a84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('uname',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('latitude',
               existing_type=sa.NUMERIC(precision=8, scale=6),
               nullable=True)
        batch_op.alter_column('longitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=True)
        batch_op.alter_column('verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('salt',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('xp',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('xp',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('salt',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('longitude',
               existing_type=sa.NUMERIC(precision=9, scale=6),
               nullable=False)
        batch_op.alter_column('latitude',
               existing_type=sa.NUMERIC(precision=8, scale=6),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.alter_column('uname',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###
