"""neuster Stand

Revision ID: c768245c23a4
Revises: 3c0dc0b9a158
Create Date: 2025-01-09 12:35:11.887416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c768245c23a4'
down_revision = '3c0dc0b9a158'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tree_type_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'tree_types', ['tree_type_id'], ['id'])
        batch_op.drop_column('tree_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tree_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tree_type_id')

    # ### end Alembic commands ###
