"""neuster Stand

Revision ID: e40a4c4fad67
Revises: c768245c23a4
Create Date: 2025-03-11 11:53:42.195165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e40a4c4fad67'
down_revision = 'c768245c23a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree_types', schema=None) as batch_op:
        batch_op.drop_column('co2_compensation_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('co2_compensation_rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
